### ISSUE TITLE
relying on a library without a release in a security product?

### ISSUE THREAD

**Issue by darix** [smuellerDD/esdm#1]
while packaging esdm for opensuse (hi from lars too) i noticed that protobuf-c-rpc library is not released yet. is there no released library that we can use?

**Comment by smuellerDD** [comment]
Am Mittwoch, 11. Mai 2022, 16:36:16 CEST schrieb darix:

Hi darix,

> while packaging esdm for opensuse (hi from lars too) i noticed that
> protobuf-c-rpc library is not released yet. is there no released library
> that we can use?

The protobuf-c-rpc code used to be part of the protobuf-c code distribution 
and thus was part of distributions. It was just separated soem time ago. Thus 
it looks to be as viable code.

Yet, I am having some issues with the library around threading. Thus it is on 
my plan to eventually replace it with my own code.

Ciao
Stephan

**Comment by darix** [comment]
I opened a bug  with the library if they could tag a release. but no answer yet.

**Comment by smuellerDD** [comment]
Am Donnerstag, 12. Mai 2022, 12:36:52 CEST schrieb darix:

Hi darix,

> I opened a bug  with the library if they could tag a release. but no answer
> yet.

Thank you. I also opened a bug there for another fix. 

Yet, I am not thinking using this library is the right strategy. The last 
commits / changes were from 2019. Then it is not nice regarding multi-
threading. I think I need to replace it.

Ciao
Stephan

**Comment by smuellerDD** [comment]
The protobuf-c-rpc is replaced with a local security-concious RPC implementation.

**Comment by smuellerDD** [comment]
Am Dienstag, 31. Mai 2022, 14:16:34 CEST schrieb darix:

Hi darix,

> Preliminary package now found at
> https://build.opensuse.org/package/show/home:darix:playground/esdm
> 
> Waiting for a new tag before pushing it further. this one now builds against
> the git master HEAD.

Thank you very much. Note, the current git HEAD is NOT production ready yet. I 
have 2 bugs still lingering that I am hunting down.

Thus, thanks for waiting until a release.

Ciao
Stephan

**Comment by darix** [comment]
i could split it up like this. but based on the size of the packages I do not see the need.

reasons for the current packaging

1. https://en.opensuse.org/openSUSE:Shared_library_packaging_policy
2. if those 3 daemons would pull in higly different dependencies (and e.g. one would have a much larger dependency tree) I would split them up. but the current package is only 165k installed 337kb for `esdm libesdm0 libesdm_rpc_client0 libjitterentropy3` I did not feel the need to do that. Do you forsee the use case where an user might want just esdm-server ? 

I am happy to split up the daemons into 3 packages if you really want.

Another option is i can have Recommends as an attribute in the package to optionally also install the getentropy library when esdm installed.

One change I would recommend is either an `esdm.target` or making the subservices `PartOf=esdm.service`


then you can do something like:

```
systemctl enable esdm-cuse-urandom
systemctl start esdm.service
```

and all parts of esdm which should be started would automatically be started:

and you can do

```
systemctl restart esdm.service
``` 

and it would restart all parts

I do that here e.g.

https://build.opensuse.org/package/show/home:darix:apps/gitlab-ce

**Comment by smuellerDD** [comment]
Am Mittwoch, 1. Juni 2022, 19:38:16 CEST schrieb darix:

Hi darix,

> i could split it up like this. but based on the size of the packages I do
> not see the need.
> 
> reasons for the current packaging
> 
> 1. https://en.opensuse.org/openSUSE:Shared_library_packaging_policy
> 2. if those 3 daemons would pull in higly different dependencies (and e.g.
> one would have a much larger dependency tree) I would split them up. but
> the current package is only 165k installed 337kb for `esdm libesdm0
> libesdm_rpc_client0 libjitterentropy3` I did not feel the need to do that.
> Do you forsee the use case where an user might want just esdm-server ?

Well, eventually I plan other clients like a virtio client.

But I am happy to follow your lead, all I try is to point out the conceptual 
structure and the individual components.
> 
> I am happy to split up the daemons into 3 packages if you really want.
> 
> Another option is i can have Recommends as an attribute in the package to
> optionally also install the getentropy library when esdm installed.

Maybe we should leave one package then.
> 
> One change I would recommend is either an `esdm.target` or making the
> subservices `PartOf=esdm.service`

Uhm, considering that other clients may appear, I did not want to restart the 
esdm-server when the cuse clients restart.
> 
> 
> then you can do something like:
> 
> ```
> systemctl enable esdm-cuse-urandom
> systemctl start esdm.service
> ```
> 
> and all parts of esdm which should be started would automatically be
> started:
> 
> and you can do
> 
> ```
> systemctl restart esdm.service
> ```
> 
> and it would restart all parts
> 
> I do that here e.g.
> 
> https://build.opensuse.org/package/show/home:darix:apps/gitlab-ce


Ciao
Stephan

**Comment by smuellerDD** [comment]
Ok, let us leave all as it is. Thanks.
