### ISSUE TITLE
adapt ESDM_SEED_BUFFER_INIT_ADD_BITS in kernel module for ais2031 and oversample_es flag

### ISSUE THREAD

**Issue by thillux** [smuellerDD/esdm#12]
Otherwise buffer sizes mismatch on communication between esdm and kernel modules.

**Comment by thillux** [comment]
May also add packed attribute, like:

```
diff --git a/addon/linux_esdm_es/esdm_es_mgr_cb.h b/addon/linux_esdm_es/esdm_es_mgr_cb.h
index 37f5b4f..5b01cc1 100644
--- a/addon/linux_esdm_es/esdm_es_mgr_cb.h
+++ b/addon/linux_esdm_es/esdm_es_mgr_cb.h
@@ -22,7 +22,7 @@ enum esdm_internal_es {
 struct entropy_buf {
        u8 e[ESDM_DRNG_INIT_SEED_SIZE_BYTES];
        u32 e_bits;
-};
+} __attribute__ ((__packed__));
 
 void esdm_reset_state(enum esdm_internal_es es);
 
diff --git a/esdm/esdm_es_mgr_cb.h b/esdm/esdm_es_mgr_cb.h
index 0f9fd62..20ef803 100644
--- a/esdm/esdm_es_mgr_cb.h
+++ b/esdm/esdm_es_mgr_cb.h
@@ -63,12 +63,12 @@ enum esdm_external_es {
 struct entropy_es {
        uint8_t e[ESDM_DRNG_INIT_SEED_SIZE_BYTES];
        uint32_t e_bits;
-};
+} __attribute__ ((__packed__));
 
 struct entropy_buf {
        struct entropy_es entropy_es[esdm_ext_es_last];
        time_t now;
-};
+} __attribute__ ((__packed__));
 
 /*
  * struct esdm_es_cb - callback defining an entropy source
```

**Comment by smuellerDD** [comment]
Am Donnerstag, 8. Juni 2023, 19:59:31 CEST schrieb Markus Theil:

Hi Markus,

> May also add packed attribute, like:

Thanks for the patch. But why do you think the packed attribute should be 
added here? We are working on the very same machine where the definitions and 
alignments of buffers should be the same, no?


Ciao
Stephan

**Comment by thillux** [comment]
Hi Stephan,

I think your right regarding the padding. I just had patched this in good will, when hitting the ais2031 + oversample_es issue. It has probably no effect.

BR
Markus

**Comment by smuellerDD** [comment]
I think I fixed the issue with respect to the dissimilar buffer sizes now.
