### ISSUE TITLE
esdm-cuse-random continues to deliver "random" numbers, when esdm-server is stopped

### ISSUE THREAD

**Issue by thillux** [smuellerDD/esdm#15]
Test:
1. cat /dev/random
2. systemctl stop esdm-server

**Comment by smuellerDD** [comment]
That would be expected:

1. cuse_random.c:main opens the "real" /dev/random and stores the FD into random_fd.
2. That fd is now used as "fallback fd" in esdm_cuse_read_block to invoke the common service handler esdm_cuse_read_internal
3, The common service handler does:
```
		/*
		 * If call to the ESDM server failed, let us fall back to the
		 * fallback file descriptor. Yet, we do not cover for short
		 * reads as this entire CUSE handling is prone to short reads
		 * as outlined below. Thus, the caller needs to handle this
		 * appropriately.
		 */
		if (ret < 0 && fallback_fd > -1) {
			logger(LOGGER_VERBOSE, LOGGER_C_CUSE,
			       "Use fallback to provide data due to RPC error code %zd\n",
			       ret);
			ret = read(fallback_fd, tmpbuf, todo);
		}
```
to ensure an uninterrupted delivery of random numbers. To me I found the availability of random numbers of higher value than the compliance of them to certain standards.

If you disagree with that, let us have a short discussion, perhaps we can add a command line flag to the cuse daemons to allow the admin to disable the fallback handling.

**Comment by smuellerDD** [comment]
Side note: this handling allows a restart of the ESDM server without loosing operational service to all user space that requires random numbers.

**Comment by thillux** [comment]
We currently plan to use esdm-server directly via rpc, so this can be closed for now.
