### ISSUE TITLE
Race condition on /dev/esdm_es

### ISSUE THREAD

**Issue by thillux** [smuellerDD/esdm#22]
If esdm_es is loaded as a kernel module at some point in time during boot and esdm-server gets started independently, a race condition exists. Sometimes esdm-server finds kernel entropy sources, sometimes not.

Possible fixes/workarounds:
- Add condition to systemd-service to check if /dev/esdm_es exists before starting esdm-server, but only if kernel support is compiled in
- Periodically retry opening/finding /dev/esdm_es in esdm-server

**Comment by thillux** [comment]
I mainly notice this issue on slower ARM devices.

**Comment by smuellerDD** [comment]
Am Donnerstag, 29. Juni 2023, 16:53:58 CEST schrieb Markus Theil:

Hi Markus,

> If esdm_es is loaded as a kernel module at some point in time during boot
> and esdm-server gets started independently, a race condition exists.
> Sometimes esdm-server finds kernel entropy sources, sometimes not.
> 
> Possible fixes/workarounds:
> - Add condition to systemd-service to check if /dev/esdm_es exists before
> starting esdm-server, but only if kernel support is compiled in -
> Periodically retry opening/finding /dev/esdm_es in esdm-server

I think the latter one should be used, but I suggest to enable this only after 
a command line option is set to avoid the polling operation on systems where 
it is known to not return anything. What do you think?

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Freitag, 30. Juni 2023, 14:33:05 CEST schrieb Markus Theil:

Hi Markus,

I just pushed a patch - please try.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Montag, 3. Juli 2023, 12:07:38 CEST schrieb Markus Theil:

Hi Markus,

> Hi Stephan,
> I tested your commit and it only works for me, if I add -u root to my
> esdm-server invocation. Otherwise esdm-server is not able to open
> /dev/esdm_es is the module is inserted after the start of esdm-server in my
> short test. BR
> Markus


You are right, because the ESDM drops its privileges during initialization. 
Thus it cannot open /dev/esdm_es any more.

Would you think it is ok that the ESDM server waits completely during 
initialization until /dev/esdm_es becomes available? Otherwise it becomes 
tricky to open the /dev/esdm_es after the initialization and still keeping the 
ESDM without any privileges.

Ciao
Stephan

**Comment by thillux** [comment]
Hi Stephan,
at least for my/our use case it would be totally fine for esdm-server to behave like you suggest.
BR
Markus

**Comment by smuellerDD** [comment]
Am Montag, 3. Juli 2023, 19:11:03 CEST schrieb Markus Theil:

Hi Markus,

> Hi Stephan,
> at least for my/our use case it would be totally fine for esdm-server to
> behave like you suggest. BR
> Markus

Have a look now.

Ciao
Stephan

**Comment by thillux** [comment]
My current understanding is, that DeviceAllow=/dev/esdm/es only works, if /dev/esdm_es is present at service start time. Otherwise access to /dev/esdm_es is blocked. I currently try to allow char-esdm_es, as this should work also on future devices of this class.

**Comment by smuellerDD** [comment]
Am Dienstag, 4. Juli 2023, 12:52:44 CEST schrieb Markus Theil:

Hi Markus,

> My current understanding is, that DeviceAllow=/dev/esdm/es only works, if

esdm/es? you mean esdm_es?

> /dev/esdm_es is present at service start time. Otherwise access to
> /dev/esdm_es is blocked. I currently try to allow char-esdm_es, as this
> should work also on future devices of this class.


Ciao
Stephan

**Comment by thillux** [comment]
The patch above worked for me.

**Comment by smuellerDD** [comment]
Patch applied, thanks.
