### ISSUE TITLE
Running into fuse limitation

### ISSUE THREAD

**Issue by thillux** [smuellerDD/esdm#36]
When running ESDM and some /dev/random poller on my notebook, suspend no longer works. ESDM uses all fuse daemons. In the example here, I used jitterentropy-rngd as poller (just in order to have an easy reproducer).

**Steps to reproduce:**
1) Start esdm with all fuse/cuse daemons
2) Start jitterentropy-rngd
3) Enter suspend (I do this with "systemctl suspend")

**Observed behavior:**
Suspend is entered after a long waiting time and sometimes never.

```
[ 2754.945068] PM: suspend entry (s2idle)
[ 2754.951728] Filesystems sync: 0.006 seconds
[ 2754.955664] Freezing user space processes
[ 2774.963892] Freezing user space processes failed after 20.008 seconds (1 tasks refusing to freeze, wq_busy=0):
[ 2774.964260] task:jitterentropy-r state:D stack:0     pid:527252 ppid:1      flags:0x00004006
[ 2774.964355] Call Trace:
[ 2774.964362]  <TASK>
[ 2774.964377]  __schedule+0x388/0x1390
[ 2774.964418]  schedule+0x5e/0xd0
[ 2774.964439]  request_wait_answer+0xd1/0x2a0 [fuse]
[ 2774.964501]  ? __pfx_autoremove_wake_function+0x10/0x10
[ 2774.964526]  fuse_simple_request+0x18f/0x2b0 [fuse]
[ 2774.964583]  fuse_file_poll+0x1a5/0x210 [fuse]
[ 2774.964657]  do_select+0x352/0x820
[ 2774.964697]  ? __pfx_pollwake+0x10/0x10
[ 2774.964758]  core_sys_select+0x236/0x450
[ 2774.964806]  do_pselect.constprop.0+0xe9/0x180
[ 2774.964832]  __x64_sys_pselect6+0x4c/0x70
[ 2774.964849]  do_syscall_64+0x3b/0x90
[ 2774.964868]  entry_SYSCALL_64_after_hwframe+0x6e/0xd8
[ 2774.964880] RIP: 0033:0x7f4981a5ce94
[ 2774.964966] RSP: 002b:00007ffc5724e1f0 EFLAGS: 00000246 ORIG_RAX: 000000000000010e
[ 2774.964980] RAX: ffffffffffffffda RBX: 0000000000000004 RCX: 00007f4981a5ce94
[ 2774.964990] RDX: 00007ffc5724e280 RSI: 0000000000000000 RDI: 0000000000000004
[ 2774.964998] RBP: 0000000000000000 R08: 0000000000000000 R09: 0000000000000000
[ 2774.965005] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000000
[ 2774.965012] R13: 0000000000000000 R14: 0000563709d4ac30 R15: 00007ffc5724e280
[ 2774.965037]  </TASK>
```

**Comment by thillux** [comment]
I currently think, this is a kernel limitation. Just wanted to let you know about it.

**Comment by thillux** [comment]
This seems to be an old but unsolved problem: https://lkml.iu.edu/hypermail/linux/kernel/1108.3/00707.html

**Comment by thillux** [comment]
Possible idea for workaround: wake all pollers periodically e.g. after 2s?

**Comment by smuellerDD** [comment]
Am Samstag, 21. Oktober 2023, 10:07:25 CEST schrieb Markus Theil:

Hi Markus,

> Possible idea for workaround: wake all pollers periodically e.g. after 2s?

What do you think about the solution in patch https://github.com/smuellerDD/
esdm/commit/926eca2031d0f777113ed2ff242cc9d3e8124b2b ?

Ciao
Stephan

**Comment by thillux** [comment]
Hi Stephan

I added some more changes in #37 in order to remove the shell dependency, add resume handling and some fixes for NixOS.
If esdm-server is killed forcefully, it does not seem to recover, when started with the pid file option. Maybe the pid file should be cleaned up in the systemd unit unconditionally before starting esdm-server?

BR
Markus

**Comment by thillux** [comment]
I forgot one thing: your path improves suspend handling for me! I haven't seen the warning above.
