### ISSUE TITLE
ESDM stalls on delivering random bytes to client process

### ISSUE THREAD

**Issue by thillux** [smuellerDD/esdm#49]
Hi Stephan,

I currently test with my little tool from yesterday:
```c++
#include <esdm/esdm_rpc_client.h>

int main(void) {
		const size_t buf_size = 32;
		while(true) {
				unsigned char buf[buf_size];
				esdm_rpcc_init_unpriv_service(NULL);
				esdm_rpcc_get_random_bytes_full(buf, buf_size);
				esdm_rpcc_fini_unpriv_service();
		}
		return 0;
}
```

After a small amount of time (typically far less than 1 minute), both this tool and esdm-server cause 0% CPU utilization and no random numbers pass between each other. This stays the same until I trigger esdm-server with another request from a different process or continue the test process after stopping and displaying the current backtrace in gdb (always in read/write on the client side).

**Comment by thillux** [comment]
I also have my kernel in suspicion, as the socket timeouts may do not work for me (tested with 6.6.41 and 6.10.0).

**Comment by thillux** [comment]
After some debugging, it seems, that the worker thread processing my request is not started, when I see such stall.

I've added a debug print to esdm_rpcs_handler and can't see it, when the client hangs:

```
ESDM (17:40:54) (ESDM hdl_rpc7) Verbose - Threading support: ESDM (17:40:54) (ESDM hdl_rpc8) Debug - RPC: Run worker thread for FD 8
Thread 1 completed
ESDM (17:40:54) (ESDM hdl_rpc8) Debug: Reading 14 bytes, already consumed 14 bytes
ESDM (17:40:54) (ESDM hdl_rpc8) Debug - RPC: Server received: message length 2, message index 4, request ID 0
ESDM (17:40:54) (ESDM hdl_rpc8) Debug - DRNG: Using DRNG instance on node 9 to service generate request
ESDM (17:40:54) (ESDM hdl_rpc8) Debug - RPC: Server sending: server status 0, message length 36, message index 4, request ID 0
ESDM (17:40:54) (ESDM hdl_rpc8) Debug2 - RPC: 2 bytes written
ESDM (17:40:54) (ESDM hdl_rpc8) Debug2 - RPC: 2 bytes written
ESDM (17:40:54) (ESDM hdl_rpc8) Debug2 - RPC: 32 bytes written
ESDM (17:40:54) (ESDM hdl_rpc8) Debug2: 52 bytes written
ESDM (17:40:54) (ESDM hdl_rpc8) Debug - RPC: Closing incoming connection for FD 8
ESDM (17:40:54) (ESDM hdl_rpc8) Verbose - Threading support: Thread 0 completed
ESDM (17:40:54) (ESDM unpriv_rpc) Debug - RPC: Processing new incoming connection for FD 7
ESDM (17:40:54) (ESDM unpriv_rpc) Verbose - Threading support: Thread 0 for thread group 0 assigned
ESDM (17:40:54) (ESDM hdl_rpc8) Debug - RPC: Run worker thread for FD 7
ESDM (17:40:54) (ESDM hdl_rpc7) Debug: Reading 14 bytes, already consumed 14 bytes
ESDM (17:40:54) (ESDM hdl_rpc7) Debug - RPC: Server received: message length 2, message index 4, request ID 0
ESDM (17:40:54) (ESDM hdl_rpc7) Debug - DRNG: Using DRNG instance on node 9 to service generate request
ESDM (17:40:54) (ESDM hdl_rpc7) Debug - RPC: Server sending: server status 0, message length 36, message index 4, request ID 0
ESDM (17:40:54) (ESDM hdl_rpc7) Debug2 - RPC: 2 bytes written
ESDM (17:40:54) (ESDM hdl_rpc7) Debug2 - RPC: 2 bytes written
ESDM (17:40:54) (ESDM hdl_rpc7) Debug2 - RPC: 32 bytes written
ESDM (17:40:54) (ESDM hdl_rpc7) Debug2: 52 bytes written
ESDM (17:40:54) (ESDM hdl_rpc7) Debug - RPC: Closing incoming connection for FD 7
ESDM (17:40:54) (ESDM hdl_rpc7) Verbose - Threading support: Thread 0 completed
ESDM (17:40:54) (ESDM unpriv_rpc) Debug - RPC: Processing new incoming connection for FD 8
ESDM (17:40:54) (ESDM unpriv_rpc) Verbose - Threading support: Thread 0 for thread group 0 assigned
ESDM (17:41:57) (ESDM krnl_feed) Debug - DRNG: reseed triggered by system events for DRNG on node 3
ESDM (17:41:57) (ESDM krnl_feed) Debug - Entropy Source: Jitter RNG ES monitor: buffer slot 4 exhausted
ESDM (17:41:57) (ESDM krnl_feed) Debug - Entropy Source: obtained 256 bits of entropy from synchronous Jitter RNG noise source instance
ESDM (17:41:57) (ESDM krnl_feed) Debug - Entropy Source: obtained 8 bits of entropy from CPU RNG entropy source
ESDM (17:41:57) (ESDM krnl_feed) Debug - Entropy Source: obtained 128 bits of entropy from kernel RNG noise source
ESDM (17:41:57) (ESDM krnl_feed) Debug - Entropy Source: obtained 128 bits of entropy from /dev/hwrng RNG entropy source
ESDM (17:41:57) (ESDM krnl_feed) Debug - Entropy Source: obtained 0 bits by collecting 0 bits of entropy from aux pool, 0 bits of entropy remaining
ESDM (17:41:57) (ESDM krnl_feed) Debug - DRNG: seeding regular DRNG with 264 bytes
ESDM (17:41:57) (ESDM krnl_feed) Debug - DRNG: regular DRNG stats since last seeding: 120 secs; generate calls: 1048575
ESDM (17:41:57) (ESDM krnl_feed) Debug - DRNG: regular DRNG fully seeded
ESDM (17:41:57) (ESDM krnl_feed) Debug - DRNG: Using DRNG instance on node 2 to service generate request
ESDM (17:41:57) (ESDM krnl_feed) Debug - ESDM server: /dev/random opened to insert entropy
ESDM (17:41:57) (ESDM krnl_feed) Debug - ESDM server: Entropy data with rate 0 bits added
```

There is no run confirmation log after the last:
```
ESDM (17:40:54) (ESDM unpriv_rpc) Verbose - Threading support: Thread 0 for thread group 0 assigned
```

**Comment by thillux** [comment]
Hi Stephan,

due to a race condition, sometimes the worker thread is notified via its condition variable, when its not waiting on the condition variable. I've tested with a timedwait of e.g. 20ms on the condition variables and cannot reproduce the stall afterwards.

BR
Markus

**Comment by thillux** [comment]
What a ride ^^. Took my simple mind the whole day to understand this :)

**Comment by smuellerDD** [comment]
Am Donnerstag, 25. Juli 2024, 19:16:48 MESZ schrieb Markus Theil:

Hi Markus,

> Hi Stephan,
> 
> due to a race condition, sometimes the worker thread is notified via its
> condition variable, when its not waiting on the condition variable. I've
> tested with a timedwait of e.g. 20ms on the condition variables and cannot
> reproduce the stall afterwards.
> 

But I am wondering who causes that stall? Why is the signal not coming 
through? The signal is pthread_cond_broadcast.

Ahhh, I think I see the issue. The following code is used in thread_worker():

/* Mark that the thread is now eligible to run */
mutex_w_unlock(&tctx->inuse);

/* Sleep to be notified */
thread_block(&tctx->worker_cv, &tctx->worker_lock);

If now a caller comes inbetween those two calls, then we have the deadlock. I 
am wondering how to fix that?

> BR
> Markus


Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Donnerstag, 25. Juli 2024, 19:19:13 MESZ schrieb Markus Theil:

Hi Markus,

> What a ride ^^. Took my simple mind the whole day to understand this :)

I think I have a solution. Your trigger code runs on my system now for 2 mins 
without problems. But I want to make more tests before applying it. If you 
could have a look too, that would be nice.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Donnerstag, 25. Juli 2024, 19:19:13 MESZ schrieb Markus Theil:

Hi Markus,

> What a ride ^^. Took my simple mind the whole day to understand this :)

This patch does not work. Please ignore.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Donnerstag, 25. Juli 2024, 19:19:13 MESZ schrieb Markus Theil:

Hi Markus,

> What a ride ^^. Took my simple mind the whole day to understand this :)

I think now I have a solution that works - the test runs for a long time now 
including proper operation.

Try attached patch.

Ciao
Stephan

**Comment by thillux** [comment]
Hi Stephan,

I don't see an attached patch in Github. My idea was to unify the in_use and worker locks.

BR Markus

**Comment by smuellerDD** [comment]
Am Freitag, 26. Juli 2024, 10:31:52 MESZ schrieb Markus Theil:

Hi Markus,

> Hi Stephan,
> 
> I don't see an attached patch in Github. My idea was to unify the in_use and
> worker locks.

Exactly - patch sent separately.
> 
> BR Markus


Ciao
Stephan

**Comment by thillux** [comment]
Hi Stephan,

the patch works so far in my test cases. A neat side effect: this decreases mean and max. latency for esdm_rpc_get_random_bytes_full. I no longer see big latency spikes in the reply times. As a direct consequence, it increases the number of requests per second against ESDM from my test code.

BR
Markus

**Comment by smuellerDD** [comment]
Am Freitag, 26. Juli 2024, 11:15:02 MESZ schrieb Markus Theil:

Hi Markus,

> Hi Stephan,
> 
> the patch works so far in my test cases. A neat side effect: this decreases
> mean and max. latency for esdm_rpc_get_random_bytes_full. I no longer see
> big latency spikes in the reply times. As a direct consequence, it
> increases the number of requests per second against ESDM from my test code.

Sweet. Of course, the unused variable is now removed from the code, too.

I had it run for 1h without any issues.

meson test is also successful (after fixing a small unrelated bug - change 
will be pushed).

Ok:                 56
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            3
Timeout:            0

I think I am going to push the patch.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Patch applied.
