### ISSUE TITLE
esdm_rpc_client.h includes local header files.

### ISSUE THREAD

**Issue by jora2802** [smuellerDD/esdm#5]
I am trying to build an extrenal rpc client. My program includes esdm_rpc_client.h. This header includes atomic.h and other headers that are not exported, thus in the current configuration I cannot use the library from out side.

**Comment by smuellerDD** [comment]
Am Dienstag, 31. Januar 2023, 13:42:16 CET schrieb jora2802:

Hi jora2802,

> I am trying to build an extrenal rpc client. My program includes
> esdm_rpc_client.h. This header includes atomic.h and other headers that are
> not exported, thus in the current configuration I cannot use the library
> from out side.

You need to point to the common/ code path for the includes as well. There are 
helpers which are needed for either client, server, or other parts.


Ciao
Stephan

**Comment by myrkr** [comment]
I think the issue here is that the esdm_rpc_client.h is installed in $DESTDIR but the required headers in common are not. We are building our tools again the destination directory of esdm not the source directory.

**Comment by smuellerDD** [comment]
Am Donnerstag, 2. Februar 2023, 03:43:12 CET schrieb Torsten Hilbrich:

Hi Torsten,

> I think the issue here is that the esdm_rpc_client.h is installed in
> $DESTDIR but the required headers in common are not. We are building our
> tools again the destination directory of esdm not the source directory.

I see.

I have pushed a change that should alleviate the issue. It installs the 
necessary headers now.

Ciao
Stephan

**Comment by jora2802** [comment]
Thank you. this fixes my build issue.
Best regards
Johannes
