### ISSUE TITLE
timeout-based companion for esdm_rpcc_get_random_bytes_full

### ISSUE THREAD

**Issue by thillux** [smuellerDD/esdm#52]
Hi Stephan,

while discussing with @myrkr about his current usage pattern of ESDM he told me about workarounds around blocking operations when the only and primary seed source (smartcard) for the auxiliary pool is unplugged for a longer time. Currently therefore esdm_rpcc_get_random_bytes_full is called in a separate thread, only launched for this invocation, which can be canceled after a given timeout. The application can deal with the situation, when no entropy is available.

Would it be ok for you, if at least for esdm_rpcc_get_random_bytes_full a timeout-based function is added, e.g. esdm_rpcc_get_random_bytes_full_w_timeout, which returns after a user defined monotonic cloud timeout?

BR
Markus

**Comment by smuellerDD** [comment]
What about https://github.com/smuellerDD/esdm/pull/53?

**Comment by thillux** [comment]
Hi Stephan,

thanks for #53! While the PR looks good from looking at its changes, let me just do some quick testing with it tomorrow.

BR
Markus

**Comment by smuellerDD** [comment]
Branch squashed and merged.
