### ISSUE TITLE
revisit time comparison operations and change to CLOCK_MONOTONIC

### ISSUE THREAD

**Issue by thillux** [smuellerDD/esdm#54]
In the past we experienced some issues with waiting on/comparing CLOCK_REALTIME based timepoints in combination with NTP timejumps. ESDM also uses CLOCK_REALTIME in some areas. My suggestion would be:

* keep CLOCK_REALTIME for logging
* keep CLOCK_REALTIME where the libc API does not permit CLOCK_MONOTONIC (mutex_w_timedlock)
* revisit all other clock_gettime, pthread_cond_wait, time() and related calls

**Comment by myrkr** [comment]
Using CLOCK_MONONTIC für timeouts is a good idea.

**Comment by thillux** [comment]
I'm nearly done in #55, but I need some input on condition variable initialization as stated in the pull request.

**Comment by smuellerDD** [comment]
Patch applied
