### ISSUE TITLE
systemd service esdm-server gets deactivated

### ISSUE THREAD

**Issue by jora2802** [smuellerDD/esdm#6]
When running as a systemd service the call to` unshare(CLONE_NEWNS | CLONE_NEWCGROUP | CLONE_NEWNET)` in _linux_isolate_namespace_ fails with EPERM and systemd deactivates the service.
This can be fixed by removing this line from frontends/server/esdm-server.service.in 
`RestrictNamespaces=yes`

**Comment by smuellerDD** [comment]
Am Donnerstag, 9. Februar 2023, 09:32:36 CET schrieb jora2802:

Hi jora2802,

> When running as a systemd service the call to` unshare(CLONE_NEWNS |
> CLONE_NEWCGROUP | CLONE_NEWNET)` in _linux_isolate_namespace_ fails with
> EPERM and systemd deactivates the service. This can be fixed by removing
> this line from frontends/server/esdm-server.service.in
> `RestrictNamespaces=yes`

Thanks a lot for the note - do you want to provide a patch?

Ciao
Stephan

**Comment by jora2802** [comment]
Hi Stephan,

thanks for the quick reply. Here you go: 
[allow-namespaces.patch](https://github.com/smuellerDD/esdm/files/10697159/allow-namespaces.patch)

Regards

Johannes

**Comment by smuellerDD** [comment]
Am Donnerstag, 9. Februar 2023, 13:38:14 CET schrieb jora2802:

Hi jora2802,

> Hi Stephan,
> 
> thanks for the quick reply. Here you go:
> [allow-namespaces.patch](https://github.com/smuellerDD/esdm/files/10697159/a
> llow-namespaces.patch)
> 
> Regards
> 
> Johannes

Appled, thanks

Ciao
Stephan

**Comment by jora2802** [comment]
Thanks for the commit!
