### ISSUE TITLE
Including esdm_rpc_client.h from C++ c

### ISSUE THREAD

**Issue by jora2802** [smuellerDD/esdm#7]
There are two issues with including esdm_rpc_client.h from C++ code:
1. new is used as a variable name, which is not allowed in C++ since it is a keyword
2. bool.h does not compile at all, but is not needed anyway.

At the moment I am using this work-around:
#define new new_
#define BOOL_H
#include <esdm/esdm_rpc_client.h>
#undef new

**Comment by smuellerDD** [comment]
Am Donnerstag, 16. Februar 2023, 09:05:35 CET schrieb jora2802:

Hi jora2802,

> There are two issues with including esdm_rpc_client.h from C++ code:
> 1. new is used as a variable name, which is not allowed in C++ since it is a
> keyword 2. bool.h does not compile at all, but is not needed anyway.
> 
> At the moment I am using this work-around:
> #define new new_
> #define BOOL_H

I have added a patch to prevent bool from being compiled with C++. But where 
do you see the use of the keyword new?

> #include <esdm/esdm_rpc_client.h>
> #undef new


Ciao
Stephan

**Comment by jora2802** [comment]
atomic.h:
`
/build/3.5.x-random/esdm/_/usr/include/esdm/atomic.h:219:60: error: expected ',' or '...' before 'new'
  219 | static inline int atomic_cmpxchg(atomic_t *v, int old, int new)
      |                                                            ^~~
/build/3.5.x-random/esdm/_/usr/include/esdm/atomic.h: In function 'int atomic_cmpxchg(atomic_t*, int, int)':
/build/3.5.x-random/esdm/_/usr/include/esdm/atomic.h:221:58: error: expected type-specifier before ')' token
  221 |  return __sync_val_compare_and_swap(&v->counter, old, new);
      |                                                          ^
/build/3.5.x-random/esdm/_/usr/include/esdm/atomic.h: At global scope:
/build/3.5.x-random/esdm/_/usr/include/esdm/atomic.h:231:48: error: expected ',' or '...' before 'new'
  231 | static inline int atomic_xchg(atomic_t *v, int new)
      |                                                ^~~
/build/3.5.x-random/esdm/_/usr/include/esdm/atomic.h: In function 'int atomic_xchg(atomic_t*, int)':
/build/3.5.x-random/esdm/_/usr/include/esdm/atomic.h:233:45: error: expected type-specifier before ',' token
  233 |  return __atomic_exchange_n(&v->counter, new, __ATOMIC_ACQUIRE);
`

**Comment by smuellerDD** [comment]
Am Donnerstag, 16. Februar 2023, 18:23:01 CET schrieb jora2802:

Hi jora2802,

thanks for the pointer - I pushed a fix that alters the variable name.

Ciao
Stephan

**Comment by jora2802** [comment]
Thank you, latest commit fixes my issues.
