### ISSUE TITLE
Dangerous usage of the min_t macro

### ISSUE THREAD

**Issue by jora2802** [smuellerDD/esdm#8]
Definition of the min_t macro:

`#define min_t(type, a, b)   ((type)a < (type)b) ? (type)a : (type)b`

This is no problem when a and b are variables or constants, but if they are functions, the functions are potentially executed twice. If those functions will yield different results at first and second execution, the macro wil not work as intended.

An example can be observed in this code snippet (from esdm_auc_get_pool) 
`
        collected_ent_bits = min_t(uint32_t, digestsize_bits,
                                  atomic_xchg(&pool->aux_entropy_bits, 0));
` 
First call to atomic_xchg(&pool->aux_entropy_bits, 0) will return the correct entropy (for the comparision), but the second call will return 0 and the subsequent code will work as if no entropy were available and fail.

**Comment by myrkr** [comment]
I would prefer if a macro like min_t or max_t would use the `do { ... } while(0)` idiom to be safe to use as a single statement especially in a if, for or else statement.

**Comment by smuellerDD** [comment]
Am Dienstag, 21. Februar 2023, 14:22:59 CET schrieb Torsten Hilbrich:

Hi Torsten,

> I would prefer if a macro like min_t or max_t would use the `do { ... }
> while(0)` idiom to be safe to use as a single statement especially in a if,
> for or else statement.

Hm, somethink like this works for Clang in all situations, but not for GCC:

_Pragma("GCC diagnostic push")					       \
	_Pragma("GCC diagnostic ignored \"-pedantic\"")			       \
	_Pragma("GCC diagnostic ignored \"-Wgnu-statement-expression-from-macro-
expansion\"")\
	({ type _a = (a);						       \
	   type _b = (b);						       \
	   _a < _b ? _a : _b; })					       \
	_Pragma("GCC diagnostic pop")

do{} while(0) does not work so far.

Any suggestions?

Ciao
Stephan

**Comment by jora2802** [comment]
Leaving aside the correct macro implementation, the macro should only be defined in one place, atm it is in helper.h and math_helper.h which is a bit confusing. The recent path is only in math_helper.h.

**Comment by smuellerDD** [comment]
Am Dienstag, 21. Februar 2023, 16:12:07 CET schrieb jora2802:

Hi jora2802,

> Leaving aside the correct macro implementation, the macro should only be
> defined in one place, atm it is in helper.h and math_helper.h which is a
> bit confusing. The recent path is only in math_helper.h.

Right, I have now changed that to only use math_helper.h. But until finding 
the proper solution for the min_t implementation, I refrain from pushing it 
:-)

Ciao
Stephan

**Comment by jora2802** [comment]
Actually I think this cannot be solved with a macro, but with two inline functions like
`inline int32_t min_signed(int32_t left, int32_t right);`  
`inline uint32_t min_usigned(uint32_t left, uint32_t right);`
Or the macros remain as they are and must not take any functions as an argument.
Both solutions will need some more code changes.

**Comment by smuellerDD** [comment]
Am Dienstag, 21. Februar 2023, 17:11:35 CET schrieb jora2802:

Hi jora2802,

Please check the new patch.

Thanks
Stephan

**Comment by jora2802** [comment]
Works fine. Thank you for your efforts.
Regards
Johannes
